Layout/EndAlignment:
  Exclude:
    - 'app/helpers/application_helper.rb'

# Offense count: 3
Metrics/AbcSize:
  Max: 46

# Offense count: 4
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 110
  Exclude:
    - 'lib/tasks/*'
    - 'spec/helpers/*'

# Offense count: 3
Metrics/CyclomaticComplexity:
  Max: 12

# Offense count: 5
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 26

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 143

# Offense count: 2
Metrics/PerceivedComplexity:
  Max: 13

# Offense count: 15
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/**/*'
    - 'app/helpers/**'
    - 'app/mailers/**'
    - 'app/models/**'
    - 'config/application.rb'
    - 'lib/*'

# Offense count: 2
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle, IgnoredMethods.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'

# Offense count: 78
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 154
  Exclude:
    - 'bin/bundle'
