default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: docker
  password: docker
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: transferbase_dev
test:
  <<: *default
  database: transferbase_test
production:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE'] %>
  host:     <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
